### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Blaidd-Drwg** [Blaidd-Drwg/ofs-convert#1]
- [x] Inode- & Block-Bitmaps
- [ ] Erstellen einer Bitmap der benutzten Blöcke, damit wir auch nach dem Überschreiben der FAT wissen, welche Blöcke wir allozieren können
(Alternative: ext4_extent_allocator, der die Block-Bitmaps der Blockgruppen anschaut)
- [x] struct extent.length zu uint16 ändern
- [x] Temporäre BGT erstellen
- [x] Bugfix: sector_no != block_no
...

Nice to have:
- Journaling
- Hardlinks unterstützen
- Metadata Checksums
- Pseudo-Extents der Länge 1 für Directories durch echte Extents ersetzen
- badblocks
- ext-Dentries in extents der fat-Dentries schreiben
Achtung: ab 4 LFN entries (Dateinamen mit >39 Zeichen) könnte es nicht mehr passen: (1 + 4) * 32 > 8 + 4 * 3 * 13
...

**Comment by Felerius** [comment]
Block Gruppen:
 * [x] Bitmaps und Inode Table initialisieren (wahrscheinlich direkt auf Disk?)
 * [x] Tracken von Statistiken (Inode/Dir entry counts, ...), z.B. als gemallocte Liste von `ext4_group_desc`
 * [x] Einfügen von Inodes in Blockgruppen (Updaten von Bitmaps, Inode Table und Group stats)
 * [x] Schreiben der fertigen GDT in allen Blockgruppen

Super Block:
 * [ ] Alle nötigen Werte setzen (und hauptsächlich erstmal finden)
 * [x] Kopien in allen Blockgruppen schreiben

Nice to have:
 * Eine Version von `sparse_super` (besser gleich v2, ist einfacher zu implementieren)
 * [x] Lazy init von Bitmaps und Inode Tables
